server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Song Service - album-related song operations
        - id: song-service-album-songs
          uri: http://localhost:8082
          predicates:
            - Path=/api/albums/*/songs,/api/albums/*/songs/**
          filters:
            - StripPrefix=0

        # Song Service - get all songs (not in album context)
        - id: song-service-all
          uri: http://localhost:8082
          predicates:
            - Path=/api/songs
            - Method=GET
          filters:
            - StripPrefix=0

        # Album Service - all album endpoints
        - id: album-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/albums/**
          filters:
            - StripPrefix=0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG