server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Song Service - album-related song operations
        - id: song-service-album-songs
          uri: lb://song-service
          predicates:
            - Path=/api/albums/*/songs,/api/albums/*/songs/**
          filters:
            - StripPrefix=0

        # Song Service - get all songs (not in album context)
        - id: song-service-all
          uri: lb://song-service
          predicates:
            - Path=/api/songs
            - Method=GET
          filters:
            - StripPrefix=0

        # Album Service - all album endpoints
        - id: album-service
          uri: lb://album-service
          predicates:
            - Path=/api/albums/**
          filters:
            - StripPrefix=0

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG